version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: event-hub-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - event-hub-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: event-hub-server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/event-hub?authSource=admin
      - JWT_SECRET=your_jwt_secret
      - JWT_EXPIRES_IN=7d
    depends_on:
      - mongodb
    networks:
      - event-hub-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: event-hub-client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - server
    networks:
      - event-hub-network

networks:
  event-hub-network:
    driver: bridge

volumes:
  mongodb_data:
